apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: always-latest01
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: example=ghcr.io/hesham131595/gitops:1.0
    argocd-image-updater.argoproj.io/example.update-strategy: latest
spec:
  project: default

  source:
    repoURL: https://github.com/hesham131595/gitops.git
    targetRevision: HEAD
    path: ./image-updater/example-app/envs/qa/
   
  destination:
    server: https://kubernetes.default.svc
    namespace: qa

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
